name: Jackpot
version: '1.0-SNAPSHOT'
main: dev.luna.jackpot.CosmicJackpot
api-version: '1.21'
commands:
  jackpot:
    description: Manage and participate in the Cosmic Jackpot mini‑game
    usage: "/<command> [buy|toggle|history|stats|help]"
    aliases: [jp]